
from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 770)
        MainWindow.setMinimumSize(QtCore.QSize(650, 450))
        MainWindow.setMaximumSize(QtCore.QSize(650, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/ico/certificate.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 85))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 85))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_help = QtWidgets.QPushButton(self.tab_2)
        self.btn_help.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_help.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_help.setFont(font)
        self.btn_help.setObjectName("btn_help")
        self.horizontalLayout_3.addWidget(self.btn_help)
        self.btn_shablon = QtWidgets.QPushButton(self.tab_2)
        self.btn_shablon.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_shablon.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_shablon.setObjectName("btn_shablon")
        self.horizontalLayout_3.addWidget(self.btn_shablon)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ed_file_excel = QtWidgets.QLineEdit(self.groupBox)
        self.ed_file_excel.setObjectName("ed_file_excel")
        self.gridLayout.addWidget(self.ed_file_excel, 1, 1, 1, 1)
        self.ed_file_pptx = QtWidgets.QLineEdit(self.groupBox)
        self.ed_file_pptx.setObjectName("ed_file_pptx")
        self.gridLayout.addWidget(self.ed_file_pptx, 0, 1, 1, 1)
        self.btn_open_file_pptx = QtWidgets.QPushButton(self.groupBox)
        self.btn_open_file_pptx.setWhatsThis("")
        self.btn_open_file_pptx.setObjectName("btn_open_file_pptx")
        self.gridLayout.addWidget(self.btn_open_file_pptx, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.btn_open_file_excel = QtWidgets.QPushButton(self.groupBox)
        self.btn_open_file_excel.setWhatsThis("")
        self.btn_open_file_excel.setObjectName("btn_open_file_excel")
        self.gridLayout.addWidget(self.btn_open_file_excel, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.cbox_excel_sheets = QtWidgets.QComboBox(self.groupBox)
        self.cbox_excel_sheets.setWhatsThis("")
        self.cbox_excel_sheets.setObjectName("cbox_excel_sheets")
        self.horizontalLayout.addWidget(self.cbox_excel_sheets)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ed_n7 = QtWidgets.QLineEdit(self.groupBox)
        self.ed_n7.setEnabled(False)
        self.ed_n7.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_n7.setObjectName("ed_n7")
        self.gridLayout_3.addWidget(self.ed_n7, 2, 4, 1, 1)
        self.chbox_n4 = QtWidgets.QCheckBox(self.groupBox)
        self.chbox_n4.setObjectName("chbox_n4")
        self.gridLayout_3.addWidget(self.chbox_n4, 3, 0, 1, 1)
        self.ed_n2 = QtWidgets.QLineEdit(self.groupBox)
        self.ed_n2.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_n2.setObjectName("ed_n2")
        self.gridLayout_3.addWidget(self.ed_n2, 1, 1, 1, 1)
        self.ed_n3 = QtWidgets.QLineEdit(self.groupBox)
        self.ed_n3.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_n3.setObjectName("ed_n3")
        self.gridLayout_3.addWidget(self.ed_n3, 2, 1, 1, 1)
        self.chbox_n3 = QtWidgets.QCheckBox(self.groupBox)
        self.chbox_n3.setChecked(True)
        self.chbox_n3.setObjectName("chbox_n3")
        self.gridLayout_3.addWidget(self.chbox_n3, 2, 0, 1, 1)
        self.chbox_n5 = QtWidgets.QCheckBox(self.groupBox)
        self.chbox_n5.setObjectName("chbox_n5")
        self.gridLayout_3.addWidget(self.chbox_n5, 0, 3, 1, 1)
        self.ed_n5 = QtWidgets.QLineEdit(self.groupBox)
        self.ed_n5.setEnabled(False)
        self.ed_n5.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_n5.setObjectName("ed_n5")
        self.gridLayout_3.addWidget(self.ed_n5, 0, 4, 1, 1)
        self.chbox_n6 = QtWidgets.QCheckBox(self.groupBox)
        self.chbox_n6.setObjectName("chbox_n6")
        self.gridLayout_3.addWidget(self.chbox_n6, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 5, 1, 1)
        self.ed_n1 = QtWidgets.QLineEdit(self.groupBox)
        self.ed_n1.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_n1.setObjectName("ed_n1")
        self.gridLayout_3.addWidget(self.ed_n1, 0, 1, 1, 1)
        self.chbox_n7 = QtWidgets.QCheckBox(self.groupBox)
        self.chbox_n7.setObjectName("chbox_n7")
        self.gridLayout_3.addWidget(self.chbox_n7, 2, 3, 1, 1)
        self.btn_seting_save = QtWidgets.QPushButton(self.groupBox)
        self.btn_seting_save.setObjectName("btn_seting_save")
        self.gridLayout_3.addWidget(self.btn_seting_save, 3, 4, 1, 1)
        self.ed_n6 = QtWidgets.QLineEdit(self.groupBox)
        self.ed_n6.setEnabled(False)
        self.ed_n6.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_n6.setObjectName("ed_n6")
        self.gridLayout_3.addWidget(self.ed_n6, 1, 4, 1, 1)
        self.chbox_n2 = QtWidgets.QCheckBox(self.groupBox)
        self.chbox_n2.setChecked(True)
        self.chbox_n2.setObjectName("chbox_n2")
        self.gridLayout_3.addWidget(self.chbox_n2, 1, 0, 1, 1)
        self.chbox_n1 = QtWidgets.QCheckBox(self.groupBox)
        self.chbox_n1.setChecked(True)
        self.chbox_n1.setObjectName("chbox_n1")
        self.gridLayout_3.addWidget(self.chbox_n1, 0, 0, 1, 1)
        self.ed_n4 = QtWidgets.QLineEdit(self.groupBox)
        self.ed_n4.setEnabled(False)
        self.ed_n4.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_n4.setObjectName("ed_n4")
        self.gridLayout_3.addWidget(self.ed_n4, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.ed_end = QtWidgets.QLineEdit(self.groupBox)
        self.ed_end.setWhatsThis("")
        self.ed_end.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_end.setObjectName("ed_end")
        self.gridLayout_2.addWidget(self.ed_end, 0, 3, 1, 1)
        self.ed_start = QtWidgets.QLineEdit(self.groupBox)
        self.ed_start.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_start.setObjectName("ed_start")
        self.gridLayout_2.addWidget(self.ed_start, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.cbox_pdf_2 = QtWidgets.QCheckBox(self.groupBox)
        self.cbox_pdf_2.setMinimumSize(QtCore.QSize(0, 0))
        self.cbox_pdf_2.setText("")
        self.cbox_pdf_2.setIconSize(QtCore.QSize(32, 32))
        self.cbox_pdf_2.setObjectName("cbox_pdf_2")
        self.horizontalLayout_7.addWidget(self.cbox_pdf_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.btn_ok = QtWidgets.QPushButton(self.groupBox)
        self.btn_ok.setWhatsThis("")
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout_2.addWidget(self.btn_ok)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget2.setFont(font)
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.textEdit = QtWidgets.QTextEdit(self.widget2)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_close_help = QtWidgets.QPushButton(self.widget2)
        self.btn_close_help.setObjectName("btn_close_help")
        self.horizontalLayout_5.addWidget(self.btn_close_help)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.widget2)
        self.widget2_2 = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget2_2.setFont(font)
        self.widget2_2.setObjectName("widget2_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget2_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget2_2)
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_4.addWidget(self.textEdit_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_close_sh = QtWidgets.QPushButton(self.widget2_2)
        self.btn_close_sh.setObjectName("btn_close_sh")
        self.horizontalLayout_9.addWidget(self.btn_close_sh)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.addWidget(self.widget2_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.widget2.setVisible(False)
        self.widget2_2.setVisible(False)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Заполнение сертификатов и дипломов v1.2"))
        self.btn_help.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Вызов справки</span></p></body></html>"))
        self.btn_help.setText(_translate("MainWindow", "Справка"))
        self.btn_shablon.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Правила подготовки шаблонов</span></p></body></html>"))
        self.btn_shablon.setText(_translate("MainWindow", "Шаблон"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Справка"))
        self.label.setText(_translate("MainWindow", "Файл Шаблона"))
        self.ed_file_excel.setText(_translate("MainWindow", "Путь к файлу"))
        self.ed_file_pptx.setText(_translate("MainWindow", "Путь к файлу"))
        self.btn_open_file_pptx.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Открыть диалоговое окно выбора шабона</span></p></body></html>"))
        self.btn_open_file_pptx.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Файл с данными"))
        self.btn_open_file_excel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Открыть диалоговое окно выбора таблицы Excel с данными</p></body></html>"))
        self.btn_open_file_excel.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Лист с данными"))
        self.cbox_excel_sheets.setToolTip(_translate("MainWindow", "<html><head/><body><p>Выбор листа с данными</p></body></html>"))
        self.ed_n7.setToolTip(_translate("MainWindow", "<html><head/><body><p>Имя колонки поля N7</p></body></html>"))
        self.ed_n7.setText(_translate("MainWindow", "G"))
        self.chbox_n4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Активировать/деактивировать поле N4</p></body></html>"))
        self.chbox_n4.setText(_translate("MainWindow", "N4"))
        self.ed_n2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Имя колонки поля N2</p></body></html>"))
        self.ed_n2.setText(_translate("MainWindow", "B"))
        self.ed_n3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Имя колонки поля N3</p></body></html>"))
        self.ed_n3.setText(_translate("MainWindow", "C"))
        self.chbox_n3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Активировать/деактивировать поле N3</p></body></html>"))
        self.chbox_n3.setText(_translate("MainWindow", "N3"))
        self.chbox_n5.setToolTip(_translate("MainWindow", "<html><head/><body><p>Активировать/деактивировать поле N5</p></body></html>"))
        self.chbox_n5.setText(_translate("MainWindow", "N5"))
        self.ed_n5.setToolTip(_translate("MainWindow", "<html><head/><body><p>Имя колонки поля N5</p></body></html>"))
        self.ed_n5.setText(_translate("MainWindow", "E"))
        self.chbox_n6.setToolTip(_translate("MainWindow", "<html><head/><body><p>Активировать/деактивировать поле N6</p></body></html>"))
        self.chbox_n6.setText(_translate("MainWindow", "N6"))
        self.ed_n1.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Имя колонки поля N1</span></p></body></html>"))
        self.ed_n1.setText(_translate("MainWindow", "A"))
        self.chbox_n7.setToolTip(_translate("MainWindow", "<html><head/><body><p>Активировать/деактивировать поле N7</p></body></html>"))
        self.chbox_n7.setText(_translate("MainWindow", "N7"))
        self.btn_seting_save.setToolTip(_translate("MainWindow", "<html><head/><body><p>Сохранить настройки названия колонок</p></body></html>"))
        self.btn_seting_save.setText(_translate("MainWindow", "По умолчанию"))
        self.ed_n6.setToolTip(_translate("MainWindow", "<html><head/><body><p>Имя колонки поля N6</p></body></html>"))
        self.ed_n6.setText(_translate("MainWindow", "F"))
        self.chbox_n2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Активировать/деактивировать поле N2</p></body></html>"))
        self.chbox_n2.setText(_translate("MainWindow", "N2"))
        self.chbox_n1.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Активировать/деактивировать поле N1</span></p></body></html>"))
        self.chbox_n1.setText(_translate("MainWindow", "N1"))
        self.ed_n4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Имя колонки поля N4</p></body></html>"))
        self.ed_n4.setText(_translate("MainWindow", "D"))
        self.label_4.setText(_translate("MainWindow", " Диапазон С  "))
        self.ed_end.setToolTip(_translate("MainWindow", "<html><head/><body><p>Диапозон завешения считывания. Если считывание осуществляется до конца таблицы в поле записываем -@</p></body></html>"))
        self.ed_end.setText(_translate("MainWindow", "-@"))
        self.ed_start.setToolTip(_translate("MainWindow", "<html><head/><body><p>Диапазон начала считывания данных из файла таблицы</p></body></html>"))
        self.ed_start.setText(_translate("MainWindow", "2"))
        self.label_5.setText(_translate("MainWindow", "  ПО  "))
        self.label_7.setText(_translate("MainWindow", "Сохранить в формате .pdf"))
        self.btn_ok.setToolTip(_translate("MainWindow", "<html><head/><body><p>Начинает процесс создания <span style=\" font-size:10pt;\">сертификатов и дипломов</span></p></body></html>"))
        self.btn_ok.setText(_translate("MainWindow", "ОК"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" background-color:transparent;\">1) В строке файл шаблона нажимаем кнопку &quot;...&quot;. В появившемся диалоговом окне выбираем заранее подготовленный шаблон документа </span>.pptx.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" background-color:transparent;\">2) В строк файл с данными нажимаем кнопку &quot;...&quot;. В появившемся диалоговом окне выбираем файл Excel с данными для заполнения.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" background-color:transparent;\">3) В строке лист с данными выбираем имя листа книги Excel, где располагаются данные для заполнения.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" background-color:transparent;\">4) Галочками рядом с N1-N7 отмечаем необходимые поля для заполнения.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" background-color:transparent;\">5) Устанавливаем соответствия между полями для заполнения N1-N7 и названиями колонок, где расположены эти данные. Названия колонок только латинские заглавные буквы, без лишних пробелов.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" background-color:transparent;\">6) Устанавливаем диапазон заполнения данными из таблицы. Если необходимо заполнить всеми данными из таблицы, в строке &quot;по&quot; указываем -@</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" background-color:transparent;\">7) Для заполнения документов нажимаем кнопку ОК. В появившемся диалоговом окне выбираем место сохранения готовых файлов. В указанном месте создается папка, куда сохраняются заполненные сертификаты и дипломы. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><br /></p></body></html>"))
        self.btn_close_help.setText(_translate("MainWindow", "Закрыть"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" font-weight:600;\">Подготовка шаблона</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" font-weight:600;\">I Устанавливаем размер и ориентация (книжная, альбомная) у слайда.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" background-color:transparent;\">    1) Слайд свойства (параметры) слайда</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" background-color:transparent;\">    2) Настраиваем формат, размеры и ориентацию, поля слайда</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" font-weight:600;\">II Устанавливаем фоновое изображение слайда</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">    1) Щелкните правой кнопкой мыши на поле слайда и выберите Формат фона.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">    2) В области Формат фона выберите Рисунок или текстура.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">    3) В разделе Добавить рисунок из источника выберите, откуда нужно получить изображение.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-weight:600;\">III Подготавливаем слайд для автоматического заполнения</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">    1) На слайде размещаем неизменяемые элементы, такие как неизменяемый текст, печать и факсимиле ...</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">    2) В текстовых полях, где должен находится переменный текст помещаем теги в фигурных скобках. Пример, {N1}.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-weight:600;\">Пример оформления тегов. </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">Награждается:</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">{N1}</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">за участие ....</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">занявший </span>{N2} место,</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">в номинации </span>{N3}</p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">В случае если ФИО разбито на несколько колонок</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">Награждается:</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">{N1} {N2} {N3}</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">за участие ....</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">занявший </span>{N4} место,</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">в номинации </span>{N5}</p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" background-color:transparent;\">    3) Форматируем и располагаем текстовые поля так, как они должны будут выглядеть в готовом документе. Для удобства расстановки элементов теги можно помещать как в одном текстовом поле так и в нескольких. </span></p></body></html>"))
        self.btn_close_sh.setText(_translate("MainWindow", "Закрыть"))



